
name: blog post workflow
on:
 schedule:
 - cron: '0 11 * * *'
 workflow_dispatch:
 
jobs:
    update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "ELASTUFKA"
          feed_list: "https://elastufka.github.io/SAX-XRS_figures/atom.xml"
          commit_message: "Update blog posts"
          gh_token: ${{ secrets.GITHUB_TOKEN }}
