
name: blog post workflow
on:
 schedule:
 - cron: '0 11 * * *'
 workflow_dispatch:
 
jobs:
    update-readme-with-blog:
        name: Update README with latest blog posts
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - uses: gautamkrishnar/blog-post-workflow@master
            with:
              max_post_count: 4
              comment_tag_name: "ELASTUFKA"
              feed_list: "https://elastufka.github.io/SAX-XRS_figures/atom.xml"
              commit_message: "Update blog posts"
              date_format: "mmm d, yyyy"
              template: '<table><tr><td><a href="$url"><img width="140px" src="https://github.com/elastufka/SAX-XRS_figures/blob/gh-pages/images/$title/hero.png"></a></td>$newline<td><a href="$url">$title</a><br/>$date</td></tr></table>$newline'
              gh_token: ${{ secrets.GITHUB_TOKEN }}
